/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false community-env.d.ts` (hash: 1170e837f14255b684778ef7fbb6faf2)
interface __BaseEnv_Env {
	SITE_ORIGIN: string;
	SUBMISSIONS_ENABLED: string;
	GITHUB_CLIENT_ID: string;
	TURNSTILE_SITE_KEY: string;
	COMMUNITY_DB?: D1Database;
}
declare namespace Cloudflare {
	interface PreviewEnv {
		SITE_ORIGIN: string;
		SUBMISSIONS_ENABLED: string;
		GITHUB_CLIENT_ID: string;
		TURNSTILE_SITE_KEY: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_ORIGIN" | "SUBMISSIONS_ENABLED" | "GITHUB_CLIENT_ID" | "TURNSTILE_SITE_KEY">> {}
}
